import "../app/global.css";
import Header from "./components/header";
import Footer from "./components/footer";

export const metadata = {
  title: 'RectorEng',
  description: 'Generated by RectorEng Pvt Ltd',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/gg.png" />
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.description} />
      </head>
      <body>
        <Header />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
