import "../app/global.css"
import Header from "./components/header"
import Footer from "./components/footer"
export const metadata = {
  title: 'RectorEng Pvt Ltd',
  description: 'Generated by RectorEng Pvt Ltd',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Header/>
        <main>{children}</main>
        <Footer/>
        </body>
    </html>
  )
}
